world_name: prelobby

target_server: lobby
target_mode: portal

target:
  from:
    ==: Vector
    x: 6.0
    y: 111.0
    z: 46.0
  to:
    ==: Vector
    x: 8.0
    y: 116.0
    z: 46.0

spawn:
  pitch: -110.0
  yaw: 0.0